Support regular expression
julz/importas pull request #3
Opened 2021-04-01 09:23 UTC by sachaos

# Changes

- :gift: Support regular expression
- Add a test for that.

2021-04-01 11:02 UTC, julz requested changes
This looks awesome, thanks so much! Couple nits:

2021-04-01 22:06 UTC, sachaos commented on config.go
> +func (c Config) findRule(path string) *Rule {
Thank you for review.
I fixed at https://github.com/julz/importas/pull/3/commits/6439bcc50383850e9f7d7b93cd8fdacb05943ce8

2021-04-01 22:07 UTC, sachaos commented on config.go
> +	return "", fmt.Errorf("mismatch rule")
I fixed at https://github.com/julz/importas/pull/3/commits/6c1a7d79d6cdcba473f564c22423248d1f241d34

2021-04-05 14:16 UTC, merged

2021-04-05 14:16 UTC, julz commented
Thanks @sachaos this is really cool!

2021-04-05 17:39 UTC, sachaos commented
@julz Thank you!

I've created PR to golangci-lint to enable to use this feature in that.
https://github.com/golangci/golangci-lint/pull/1899